### PR TITLE
Refactored Dockerfile: thin container & can run private relay

### LINKED ISSUE #6: ENTRYPOINT vs CMD
(not entirely sure about the equivalence, hence an issue instead of a PR)

I'm using your container from docker compose, where it is convenient to be able to pass additional arguments using the [`command`](https://docs.docker.com/compose/compose-file/#command) option. If the container would specify `/usr/bin/strelaysrv` as the `ENTRYPOINT`, instead of the `CMD`, we wouldn't need to repeat the path to the binary in the `command` option.

For example, https://github.com/v2tec/watchtower, where you can just have `command: --interval 30` because the path to the binary is configured in the Dockerfile as `ENTRYPOINT ["/watchtower"]`.

### PR DESCRIPTION
**Pull request by delfer**
Also closes https://github.com/kylemanna/docker-syncthing-relay/issues/6

### CODE REVIEW

**Comment by kylemanna** [comment]
Interested in merging this, do you have a before-vs-after comparison of final image size?  I'd imagine the images built with this pull request are much smaller.

Second, are there backwards compatability problems with people running old Docker clients?  Will it break things for existing users?  I'm hoping all the magic happens on the Docker hub build.

**Comment by kylemanna** [comment]
Also the travis-ci test broke at some point.  It looks like it's the result of the `CMD` -> `ENTRYPOINT` change.

**Comment by kylemanna** [comment]
The size savings is substantial going from 279MB -> 14MB:

    REPOSITORY                          TAG                 IMAGE ID            CREATED              SIZE
    strelaysrv-master-271e016           latest              617bf37417ee        29 seconds ago       279MB
    strelaysrv-thin-container-f49c56d   latest              3f64a3f3021a        About a minute ago   14MB

**Comment by delfer** [comment]
@kylemanna I've disabled failing test by specifying 3 of 4 test to execute.

> Second, are there backwards compatability problems with people running old Docker clients? Will it break things for existing users?

Thin image have the same compatibility as fat one.

**Comment by kylemanna** [comment]
Explicitly defining tests isn't acceptable.  Upstream will add/delete tests and there's *no* reason the generic tests shouldn't run on this image.  No justification was given for why it was disabled other then it now _works_.

Closer inspection on the failing test reveals a common Docker convention that we should follow unless some compelling case is presented.  So far the only reason I've seen to go from `CMD` to `ENTRYPOINT` is so that someone can skip typing the command to run when passing arguments.

More details on the [failing test](https://github.com/docker-library/official-images/blob/master/test/tests/override-cmd/run.sh) and the [README discussing consistency](https://github.com/docker-library/official-images/blob/d28cb89e79417cac50c2a8ae163a9b3b79167f79/README.md#consistency).

Please update the commit to run all generic tests and use the `CMD` argument instead of `ENTRYPOINT` and appropriate commit message and I can merge this.

Thanks!

**Comment by kylemanna** [comment]
Thought about this more, lets run with the `ENTRYPOINT`.  I'll merge it, no changes needed.

Thanks

**Pull request merged**
